### ISSUE TITLE
Multiple assertions.

### ISSUE THREAD

**Issue by phet-steele** [phetsims/molecules-and-light#161]
Due to recent axon/tandem changes?

```
molecules-and-light : phet-io-fuzz : require.js : load
Uncaught Error: Assertion failed: Cannot register two different instances to the same id: moleculesAndLight.moleculesAndLightScreen.model.CO.vibratingProperty
Error: Assertion failed: Cannot register two different instances to the same id: moleculesAndLight.moleculesAndLightScreen.model.CO.vibratingProperty
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/assert/js/assert.js:22:13)
    at Object.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/phet-io/js/phetio.js?bust=1507917652874:512:19)
    at Object.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/phet-io/js/phetio.js?bust=1507917652874:62:14)
    at Tandem.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/tandem/js/Tandem.js?bust=1507917652874:132:36)
    at BooleanProperty.Property [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/axon/js/Property.js?bust=1507917652874:99:20)
    at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/axon/js/BooleanProperty.js?bust=1507917652874:44:14)
    at CO.Molecule [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/molecules-and-light/js/photon-absorption/model/Molecule.js?bust=1507917652874:119:30)
    at new CO (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/molecules-and-light/js/photon-absorption/model/molecules/CO.js?bust=1507917652874:37:14)
    at PhotonAbsorptionModel.updateActiveMolecule (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/molecules-and-light/js/photon-absorption/model/PhotonAbsorptionModel.js?bust=1507917652874:382:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/molecules-and-light/js/photon-absorption/model/PhotonAbsorptionModel.js?bust=1507917652874:123:12)
Approximately 10/13/2017, 11:29:06 AM

molecules-and-light : phet-io-fuzz : require.js : load
Uncaught Error: Assertion failed: Cannot register two different instances to the same id: moleculesAndLight.moleculesAndLightScreen.model.O3.vibratingProperty
Error: Assertion failed: Cannot register two different instances to the same id: moleculesAndLight.moleculesAndLightScreen.model.O3.vibratingProperty
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/assert/js/assert.js:22:13)
    at Object.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/phet-io/js/phetio.js?bust=1507917652874:512:19)
    at Object.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/phet-io/js/phetio.js?bust=1507917652874:62:14)
    at Tandem.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/tandem/js/Tandem.js?bust=1507917652874:132:36)
    at BooleanProperty.Property [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/axon/js/Property.js?bust=1507917652874:99:20)
    at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/axon/js/BooleanProperty.js?bust=1507917652874:44:14)
    at O3.Molecule [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/molecules-and-light/js/photon-absorption/model/Molecule.js?bust=1507917652874:119:30)
    at new O3 (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/molecules-and-light/js/photon-absorption/model/molecules/O3.js?bust=1507917652874:55:14)
    at PhotonAbsorptionModel.updateActiveMolecule (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/molecules-and-light/js/photon-absorption/model/PhotonAbsorptionModel.js?bust=1507917652874:407:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/molecules-and-light/js/photon-absorption/model/PhotonAbsorptionModel.js?bust=1507917652874:123:12)
Approximately 10/13/2017, 11:29:06 AM

molecules-and-light : phet-io-fuzz : require.js : run
Uncaught Error: Assertion failed: Cannot register two different instances to the same id: moleculesAndLight.moleculesAndLightScreen.model.CO.vibratingProperty
Error: Assertion failed: Cannot register two different instances to the same id: moleculesAndLight.moleculesAndLightScreen.model.CO.vibratingProperty
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/assert/js/assert.js:22:13)
    at Object.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/phet-io/js/phetio.js?bust=1507917652874:512:19)
    at Object.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/phet-io/js/phetio.js?bust=1507917652874:62:14)
    at Tandem.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/tandem/js/Tandem.js?bust=1507917652874:132:36)
    at BooleanProperty.Property [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/axon/js/Property.js?bust=1507917652874:99:20)
    at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/axon/js/BooleanProperty.js?bust=1507917652874:44:14)
    at CO.Molecule [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/molecules-and-light/js/photon-absorption/model/Molecule.js?bust=1507917652874:119:30)
    at new CO (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/molecules-and-light/js/photon-absorption/model/molecules/CO.js?bust=1507917652874:37:14)
    at PhotonAbsorptionModel.updateActiveMolecule (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/molecules-and-light/js/photon-absorption/model/PhotonAbsorptionModel.js?bust=1507917652874:382:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/molecules-and-light/js/photon-absorption/model/PhotonAbsorptionModel.js?bust=1507917652874:123:12)
Approximately 10/13/2017, 11:29:06 AM

molecules-and-light : phet-io-fuzz : require.js : run
Uncaught Error: Assertion failed: Cannot register two different instances to the same id: moleculesAndLight.moleculesAndLightScreen.model.O3.vibratingProperty
Error: Assertion failed: Cannot register two different instances to the same id: moleculesAndLight.moleculesAndLightScreen.model.O3.vibratingProperty
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/assert/js/assert.js:22:13)
    at Object.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/phet-io/js/phetio.js?bust=1507917652874:512:19)
    at Object.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/phet-io/js/phetio.js?bust=1507917652874:62:14)
    at Tandem.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/tandem/js/Tandem.js?bust=1507917652874:132:36)
    at BooleanProperty.Property [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/axon/js/Property.js?bust=1507917652874:99:20)
    at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/axon/js/BooleanProperty.js?bust=1507917652874:44:14)
    at O3.Molecule [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/molecules-and-light/js/photon-absorption/model/Molecule.js?bust=1507917652874:119:30)
    at new O3 (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/molecules-and-light/js/photon-absorption/model/molecules/O3.js?bust=1507917652874:55:14)
    at PhotonAbsorptionModel.updateActiveMolecule (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/molecules-and-light/js/photon-absorption/model/PhotonAbsorptionModel.js?bust=1507917652874:407:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/molecules-and-light/js/photon-absorption/model/PhotonAbsorptionModel.js?bust=1507917652874:123:12)
Approximately 10/13/2017, 11:29:06 AM

molecules-and-light : phet-io-fuzz : require.js : run
Uncaught Error: Assertion failed: Cannot register two different instances to the same id: moleculesAndLight.moleculesAndLightScreen.view.observationWindow.photonEmitterNode.infraredSlider.enabledProperty
Error: Assertion failed: Cannot register two different instances to the same id: moleculesAndLight.moleculesAndLightScreen.view.observationWindow.photonEmitterNode.infraredSlider.enabledProperty
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/assert/js/assert.js:22:13)
    at Object.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/phet-io/js/phetio.js?bust=1507920006089:512:19)
    at Object.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/phet-io/js/phetio.js?bust=1507920006089:62:14)
    at Tandem.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/tandem/js/Tandem.js?bust=1507920006089:132:36)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/axon/js/Property.js?bust=1507920006089:99:20)
    at new HSlider (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/sun/js/HSlider.js?bust=1507920006089:112:58)
    at new EmissionRateControlSliderNode (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/molecules-and-light/js/photon-absorption/view/EmissionRateControlSliderNode.js?bust=1507920006089:57:38)
    at PhotonEmitterNode.updateImage (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/molecules-and-light/js/photon-absorption/view/PhotonEmitterNode.js?bust=1507920006089:119:44)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/molecules-and-light/js/photon-absorption/view/PhotonEmitterNode.js?bust=1507920006089:55:12)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1507915746113/axon/js/Emitter.js?bust=1507920006089:205:49)
Approximately 10/13/2017, 11:29:06 AM
```

**Comment by jessegreenberg** [comment]
I am unable to observer this locally, and continuous testing is showing all tests passing for molecules-and-light for a few days. Closing.
