### ISSUE TITLE
CT Emitted unexpected number of args

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#195]
```
molecules-and-light : accessibility-fuzz : require.js : run
Query: brand=phet&ea&fuzz&a11y&memoryLimit=1000
Uncaught Error: Assertion failed: Emitted unexpected number of args. Expected: 1 and received 2
Error: Assertion failed: Emitted unexpected number of args. Expected: 1 and received 2
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/assert/js/assert.js:22:13)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/axon/js/Emitter.js?bust=1553062865600:258:9)
    at O3.breakApart (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/molecules/O3.js?bust=1553062865600:137:30)
    at BreakApartStrategy.step (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/BreakApartStrategy.js?bust=1553062865600:42:21)
    at O3.step (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/Molecule.js?bust=1553062865600:247:43)
    at PhotonAbsorptionModel.stepMolecules (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/PhotonAbsorptionModel.js?bust=1553062865600:266:37)
    at PhotonAbsorptionModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/PhotonAbsorptionModel.js?bust=1553062865600:203:14)
    at first (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/joist/js/Sim.js?bust=1553062865600:213:24)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/axon/js/Emitter.js?bust=1553062865600:280:55)
    at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/joist/js/Sim.js?bust=1553062865600:916:34)
id: Bayes Chrome
Approximately 3/19/2019, 10:42:58 PM
molecules-and-light : accessibility-fuzz : require.js : run
Query: brand=phet&ea&fuzz&a11y&memoryLimit=1000
Uncaught Error: Assertion failed: Emitted unexpected number of args. Expected: 1 and received 2
Error: Assertion failed: Emitted unexpected number of args. Expected: 1 and received 2
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/assert/js/assert.js:22:13)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/axon/js/Emitter.js?bust=1553078155459:258:9)
    at O3.breakApart (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/molecules/O3.js?bust=1553078155459:137:30)
    at BreakApartStrategy.step (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/BreakApartStrategy.js?bust=1553078155459:42:21)
    at O3.step (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/Molecule.js?bust=1553078155459:247:43)
    at PhotonAbsorptionModel.stepMolecules (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/PhotonAbsorptionModel.js?bust=1553078155459:266:37)
    at PhotonAbsorptionModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/PhotonAbsorptionModel.js?bust=1553078155459:203:14)
    at first (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/joist/js/Sim.js?bust=1553078155459:213:24)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/axon/js/Emitter.js?bust=1553078155459:280:55)
    at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/joist/js/Sim.js?bust=1553078155459:916:34)
id: Bayes Chrome
Approximately 3/19/2019, 10:42:58 PM
molecules-and-light : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Emitted unexpected number of args. Expected: 1 and received 2
Error: Assertion failed: Emitted unexpected number of args. Expected: 1 and received 2
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/assert/js/assert.js:22:13)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/axon/js/Emitter.js?bust=1553082927786:258:9)
    at O3.breakApart (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/molecules/O3.js?bust=1553082927786:137:30)
    at BreakApartStrategy.step (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/BreakApartStrategy.js?bust=1553082927786:42:21)
    at O3.step (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/Molecule.js?bust=1553082927786:247:43)
    at PhotonAbsorptionModel.stepMolecules (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/PhotonAbsorptionModel.js?bust=1553082927786:266:37)
    at PhotonAbsorptionModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/PhotonAbsorptionModel.js?bust=1553082927786:203:14)
    at first (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/joist/js/Sim.js?bust=1553082927786:213:24)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/axon/js/Emitter.js?bust=1553082927786:280:55)
    at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/joist/js/Sim.js?bust=1553082927786:916:34)
id: Bayes Chrome
Approximately 3/19/2019, 10:42:58 PM
molecules-and-light : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Assertion failed: Emitted unexpected number of args. Expected: 1 and received 2
Error: Assertion failed: Emitted unexpected number of args. Expected: 1 and received 2
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/assert/js/assert.js:22:13)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/axon/js/Emitter.js?bust=1553058315889:258:9)
    at NO2.breakApart (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/molecules/NO2.js?bust=1553058315889:144:30)
    at BreakApartStrategy.step (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/BreakApartStrategy.js?bust=1553058315889:42:21)
    at NO2.step (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/Molecule.js?bust=1553058315889:247:43)
    at PhotonAbsorptionModel.stepMolecules (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/PhotonAbsorptionModel.js?bust=1553058315889:266:37)
    at PhotonAbsorptionModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/PhotonAbsorptionModel.js?bust=1553058315889:203:14)
    at first (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/joist/js/Sim.js?bust=1553058315889:213:24)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/axon/js/Emitter.js?bust=1553058315889:280:55)
    at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/joist/js/Sim.js?bust=1553058315889:916:34)
id: Bayes Chrome
Approximately 3/19/2019, 10:42:58 PM
molecules-and-light : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Assertion failed: Emitted unexpected number of args. Expected: 1 and received 2
Error: Assertion failed: Emitted unexpected number of args. Expected: 1 and received 2
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/assert/js/assert.js:22:13)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/axon/js/Emitter.js?bust=1553077738093:258:9)
    at O3.breakApart (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/molecules/O3.js?bust=1553077738093:137:30)
    at BreakApartStrategy.step (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/BreakApartStrategy.js?bust=1553077738093:42:21)
    at O3.step (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/Molecule.js?bust=1553077738093:247:43)
    at PhotonAbsorptionModel.stepMolecules (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/PhotonAbsorptionModel.js?bust=1553077738093:266:37)
    at PhotonAbsorptionModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/PhotonAbsorptionModel.js?bust=1553077738093:203:14)
    at first (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/joist/js/Sim.js?bust=1553077738093:213:24)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/axon/js/Emitter.js?bust=1553077738093:280:55)
    at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/joist/js/Sim.js?bust=1553077738093:916:34)
id: Bayes Chrome
Approximately 3/19/2019, 10:42:58 PM
molecules-and-light : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Assertion failed: Emitted unexpected number of args. Expected: 1 and received 2
Error: Assertion failed: Emitted unexpected number of args. Expected: 1 and received 2
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/assert/js/assert.js:22:13)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/axon/js/Emitter.js?bust=1553092167758:258:9)
    at O3.breakApart (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/molecules/O3.js?bust=1553092167758:137:30)
    at BreakApartStrategy.step (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/BreakApartStrategy.js?bust=1553092167758:42:21)
    at O3.step (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/Molecule.js?bust=1553092167758:247:43)
    at PhotonAbsorptionModel.stepMolecules (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/PhotonAbsorptionModel.js?bust=1553092167758:266:37)
    at PhotonAbsorptionModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/PhotonAbsorptionModel.js?bust=1553092167758:203:14)
    at first (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/joist/js/Sim.js?bust=1553092167758:213:24)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/axon/js/Emitter.js?bust=1553092167758:280:55)
    at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/joist/js/Sim.js?bust=1553092167758:916:34)
id: Bayes Chrome
Approximately 3/19/2019, 10:42:58 PM
molecules-and-light : phet-io-tests : assert
7 out of 7 tests passed. 0 failed.

Approximately 3/19/2019, 10:42:58 PM
molecules-and-light : phet-io-tests : no-assert
7 out of 7 tests passed. 0 failed.

Approximately 3/19/2019, 10:42:58 PM
molecules-and-light : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Emitted unexpected number of args. Expected: 1 and received 2
Error: Assertion failed: Emitted unexpected number of args. Expected: 1 and received 2
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/assert/js/assert.js:22:13)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/axon/js/Emitter.js?bust=1553061730871:258:9)
    at O3.breakApart (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/molecules/O3.js?bust=1553061730871:137:30)
    at BreakApartStrategy.step (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/BreakApartStrategy.js?bust=1553061730871:42:21)
    at O3.step (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/Molecule.js?bust=1553061730871:247:43)
    at PhotonAbsorptionModel.stepMolecules (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/PhotonAbsorptionModel.js?bust=1553061730871:266:37)
    at PhotonAbsorptionModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/molecules-and-light/js/photon-absorption/model/PhotonAbsorptionModel.js?bust=1553061730871:203:14)
    at first (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/joist/js/Sim.js?bust=1553061730871:213:24)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/axon/js/Emitter.js?bust=1553061730871:280:55)
    at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1553056978109/joist/js/Sim.js?bust=1553061730871:916:34)
```

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, this must have come from recent changes to emitter validation.

**Comment by jessegreenberg** [comment]
Should be fixed by the above commit.
