### ISSUE TITLE
CT Changed state on startup should be empty

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#215]
```
molecules-and-light : phet-io-tests : assert
8 out of 9 tests passed. 1 failed.
SimTests: molecules-and-light: iframe api failed:
Changed state on startup should be empty, but instead includes: moleculesAndLight.moleculesAndLightScreen.model.molecules
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570093689002/phet-io-wrappers/js/tests/SimTests.js?:115:20
    at Client.dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1570093689002/phet-io-wrappers/common/js/Client.js:432:82)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1570093689002/phet-io-wrappers/common/js/Client.js:331:24)

SimTests: molecules-and-light: iframe api failed:
Changed state should now have one item in it.
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570093689002/phet-io-wrappers/js/tests/SimTests.js?:129:24
    at Client.dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1570093689002/phet-io-wrappers/common/js/Client.js:432:82)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1570093689002/phet-io-wrappers/common/js/Client.js:331:24)

SimTests: molecules-and-light: iframe api failed:
Changed state should now have two items in it because active property changed.
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570093689002/phet-io-wrappers/js/tests/SimTests.js?:150:30
    at Client.dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1570093689002/phet-io-wrappers/common/js/Client.js:432:82)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1570093689002/phet-io-wrappers/common/js/Client.js:331:24)


id: Bayes Chrome
Approximately 10/3/2019, 3:08:09 AM
molecules-and-light : phet-io-tests : no-assert
8 out of 9 tests passed. 1 failed.
SimTests: molecules-and-light: iframe api failed:
Changed state on startup should be empty, but instead includes: moleculesAndLight.moleculesAndLightScreen.model.molecules
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570093689002/phet-io-wrappers/js/tests/SimTests.js?:115:20
    at Client.dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1570093689002/phet-io-wrappers/common/js/Client.js:432:82)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1570093689002/phet-io-wrappers/common/js/Client.js:331:24)

SimTests: molecules-and-light: iframe api failed:
Changed state should now have one item in it.
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570093689002/phet-io-wrappers/js/tests/SimTests.js?:129:24
    at Client.dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1570093689002/phet-io-wrappers/common/js/Client.js:432:82)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1570093689002/phet-io-wrappers/common/js/Client.js:331:24)

SimTests: molecules-and-light: iframe api failed:
Changed state should now have two items in it because active property changed.
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570093689002/phet-io-wrappers/js/tests/SimTests.js?:150:30
    at Client.dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1570093689002/phet-io-wrappers/common/js/Client.js:432:82)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1570093689002/phet-io-wrappers/common/js/Client.js:331:24)


id: Bayes Chrome
Approximately 10/3/2019, 3:08:09 AM
```

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe. I am not sure whether this issue is sim specific or related to PhET-iO internals. Happy to look into this but not sure where to start. Assigning to PhET-iO team first to have a look or for recommendation.

**Comment by zepumph** [comment]
This issue is related to the changes we made in ObservableArrayIO yesterday. Basically it was using reference serialization for state, and MoleculeIO was largely not being used for the array, but now we are using MoleculeIO. I will do more investigation.

**Comment by zepumph** [comment]
This test is signifying that the during startup, but after the "initialState" has been collected, some state in the `molecules` array changes. I added logging, and haven't yet found an obvious place where this is happening. I don't think it is from `updateActiveMolecule`, the only place molecules are added, so perhaps it has to do with the Molecule mutating.

**Comment by zepumph** [comment]
This issue was caused because we made all instrumented ObservableArrays that were using reference type serialization instead be dependent on their parameter type. In MAL, this.photons and this.molecules were both then utilizing `PhotonIO` and `MoleculeIO`. Before to/fromStateObjects weren't being used here.

@samreid please review the changes in the IO types (or Molecule.fromStateObject in that case). Basically I hacked out a way to get PhotonIO to support dynamic state. Really though it should use Group though. 

Since `molecules` were being now serialized as data-types instead of just phetioIDs, we got the initial state error. This was sim-specific in my opinion. Because absorptionHysteresisCountdownTime was changing after the first step even though nothing was happening in the sim. @jessegreenberg and I paired on this, and he said that the change looked good. That said please have a look at the sim-specific changes, for example now I am disposing cleared photons on reset. I think this solved a memory leak exposed (and caused) through PhET-iO, but it would be good to make sure.

@jessegreenberg also mentioned a good point, which was that the initialState test we have right now is likely too strict. We can't assume that NO state will change until you interact with the sim, which is what I do. Until we run into a case that breaks this assumption though I don't really want change the test because it has been helpful in exposing unexpected changes to the state of the sim after the initialState has already been taken.

Thanks you two!

**Comment by jessegreenberg** [comment]
> lease have a look at the sim-specific changes, for example now I am disposing cleared photons on reset

Took a look. This is a good change, thanks!

**Comment by zepumph** [comment]
@samreid instead of using your time to review this issue. I think we should focus on getting Group to a usable place, and converting this sim to use that. CT has been clear of this for some time now. Closing
