### ISSUE TITLE
CT tandem was required but not supplied

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#300]
```
molecules-and-light : phet-io-fuzz : require.js : load
https://bayes.colorado.edu/continuous-testing/snapshot-1584004705257/molecules-and-light/molecules-and-light_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584004705257/assert/js/assert.js?bust=1584007173173:22:13)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1584004705257/tandem/js/Tandem.js:113:19)
    at Emitter.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1584004705257/tandem/js/PhetioObject.js:355:17)
    at new PhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1584004705257/tandem/js/PhetioObject.js:189:10)
    at new Action (https://bayes.colorado.edu/continuous-testing/snapshot-1584004705257/axon/js/Action.js:91:5)
    at new Emitter (https://bayes.colorado.edu/continuous-testing/snapshot-1584004705257/axon/js/Emitter.js:29:5)
    at new StickyToggleButtonModel (https://bayes.colorado.edu/continuous-testing/snapshot-1584004705257/sun/js/buttons/StickyToggleButtonModel.js:39:25)
    at BooleanRoundStickyToggleButton.RoundStickyToggleButton [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1584004705257/sun/js/buttons/RoundStickyToggleButton.js:38:29)
    at new BooleanRoundStickyToggleButton (https://bayes.colorado.edu/continuous-testing/snapshot-1584004705257/sun/js/buttons/BooleanRoundStickyToggleButton.js:23:27)
    at PhotonEmitterNode.updateImage (https://bayes.colorado.edu/continuous-testing/snapshot-1584004705257/molecules-and-light/js/photon-absorption/view/PhotonEmitterNode.js:111:34)
id: Bayes Chrome
Approximately 3/12/2020, 3:18:25 AM
molecules-and-light : phet-io-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584004705257/molecules-and-light/molecules-and-light_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584004705257/assert/js/assert.js?bust=1584007173173:22:13)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1584004705257/tandem/js/Tandem.js:113:19)
    at Emitter.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1584004705257/tandem/js/PhetioObject.js:355:17)
    at new PhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1584004705257/tandem/js/PhetioObject.js:189:10)
    at new Action (https://bayes.colorado.edu/continuous-testing/snapshot-1584004705257/axon/js/Action.js:91:5)
    at new Emitter (https://bayes.colorado.edu/continuous-testing/snapshot-1584004705257/axon/js/Emitter.js:29:5)
    at new StickyToggleButtonModel (https://bayes.colorado.edu/continuous-testing/snapshot-1584004705257/sun/js/buttons/StickyToggleButtonModel.js:39:25)
    at BooleanRoundStickyToggleButton.RoundStickyToggleButton [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1584004705257/sun/js/buttons/RoundStickyToggleButton.js:38:29)
    at new BooleanRoundStickyToggleButton (https://bayes.colorado.edu/continuous-testing/snapshot-1584004705257/sun/js/buttons/BooleanRoundStickyToggleButton.js:23:27)
    at PhotonEmitterNode.updateImage (https://bayes.colorado.edu/continuous-testing/snapshot-1584004705257/molecules-and-light/js/photon-absorption/view/PhotonEmitterNode.js:111:34)
id: Bayes Chrome
Approximately 3/12/2020, 3:18:25 AM
molecules-and-light : phet-io-tests : no-assert
https://bayes.colorado.edu/continuous-testing/snapshot-1584004705257/phet-io-wrappers/phet-io-wrappers-tests.html?sim=molecules-and-light
9 out of 9 tests passed. 0 failed.

Approximately 3/12/2020, 3:18:25 AM
```

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe , fixed.
