### ISSUE TITLE
CT Cannot read property numberOfChildren of null

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#355]
```
molecules-and-light : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/studio/?sim=molecules-and-light&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecules-and-light%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1591577076110%22%2C%22timestamp%22%3A1591580744135%7D
Uncaught TypeError: Cannot read property 'numberOfChildren' of null
TypeError: Cannot read property 'numberOfChildren' of null
at removeDanglingNonElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/studio/js/PhetioElementTreeNode.js:150:38)
at removeDanglingNonElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/studio/js/PhetioElementTreeNode.js:153:11)
at Function.removePhetioElementFromTree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/studio/js/PhetioElementTreeNode.js:162:39)
at Studio.onPhetioElementRemoved (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/studio/js/Studio.js:287:43)
at phetioElementRemoved (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/studio/js/main.js:54:28)
at Client.dispatch (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/phet-io-wrappers/common/js/Client.js:469:56)
at windowMessageListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/phet-io-wrappers/common/js/Client.js:342:24)
id: Bayes Chrome
Snapshot from 6/7/2020, 6:44:36 PM

----------------------------------

molecules-and-light : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/studio/?sim=molecules-and-light&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecules-and-light%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1591577076110%22%2C%22timestamp%22%3A1591590741073%7D
Uncaught TypeError: Cannot read property 'numberOfChildren' of null
TypeError: Cannot read property 'numberOfChildren' of null
at removeDanglingNonElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/studio/js/PhetioElementTreeNode.js:150:38)
at removeDanglingNonElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/studio/js/PhetioElementTreeNode.js:153:11)
at Function.removePhetioElementFromTree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/studio/js/PhetioElementTreeNode.js:162:39)
at Studio.onPhetioElementRemoved (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/studio/js/Studio.js:287:43)
at phetioElementRemoved (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/studio/js/main.js:54:28)
at Client.dispatch (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/phet-io-wrappers/common/js/Client.js:469:56)
at windowMessageListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/phet-io-wrappers/common/js/Client.js:342:24)
id: Bayes Chrome
Snapshot from 6/7/2020, 6:44:36 PM

----------------------------------

molecules-and-light : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/studio/?sim=molecules-and-light&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecules-and-light%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1591577076110%22%2C%22timestamp%22%3A1591601231464%7D
Uncaught TypeError: Cannot read property 'numberOfChildren' of null
TypeError: Cannot read property 'numberOfChildren' of null
at removeDanglingNonElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/studio/js/PhetioElementTreeNode.js:150:38)
at removeDanglingNonElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/studio/js/PhetioElementTreeNode.js:153:11)
at Function.removePhetioElementFromTree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/studio/js/PhetioElementTreeNode.js:162:39)
at Studio.onPhetioElementRemoved (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/studio/js/Studio.js:287:43)
at phetioElementRemoved (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/studio/js/main.js:54:28)
at Client.dispatch (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/phet-io-wrappers/common/js/Client.js:469:56)
at windowMessageListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/phet-io-wrappers/common/js/Client.js:342:24)
id: Bayes Chrome
Snapshot from 6/7/2020, 6:44:36 PM

----------------------------------

molecules-and-light : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/studio/?sim=molecules-and-light&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecules-and-light%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1591577076110%22%2C%22timestamp%22%3A1591614159972%7D
Uncaught TypeError: Cannot read property 'numberOfChildren' of null
TypeError: Cannot read property 'numberOfChildren' of null
at removeDanglingNonElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/studio/js/PhetioElementTreeNode.js:150:38)
at removeDanglingNonElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/studio/js/PhetioElementTreeNode.js:153:11)
at Function.removePhetioElementFromTree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/studio/js/PhetioElementTreeNode.js:162:39)
at Studio.onPhetioElementRemoved (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/studio/js/Studio.js:287:43)
at phetioElementRemoved (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/studio/js/main.js:54:28)
at Client.dispatch (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/phet-io-wrappers/common/js/Client.js:469:56)
at windowMessageListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591577076110/phet-io-wrappers/common/js/Client.js:342:24)
id: Bayes Chrome
Snapshot from 6/7/2020, 6:44:36 PM
```

**Comment by KatieWoe** [comment]
Just informed that this is part of https://github.com/phetsims/studio/issues/134.
Closing
