### ISSUE TITLE
CT Perennial task failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#387]
```
molecules-and-light : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (molecules-and-light, brands: phet, phet-io)
Building brand: phet
Fatal error: Perennial task failed:
ModuleNotFoundError: Module not found: Error: Can't resolve '../../../../scenery-phet/js/accessibility/describers/MovementDescriber.js' in '/data/share/phet/continuous-testing/ct-snapshots/1629969913512/greenhouse-effect/js/micro/view'
at /data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/webpack/lib/Compilation.js:1773:28
at /data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/webpack/lib/NormalModuleFactory.js:811:13
at eval (eval at create (/data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
at /data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/webpack/lib/NormalModuleFactory.js:286:22
at eval (eval at create (/data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
at /data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/webpack/lib/NormalModuleFactory.js:442:22
at /data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/webpack/lib/NormalModuleFactory.js:124:11
at /data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/webpack/lib/NormalModuleFactory.js:673:25
at /data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/webpack/lib/NormalModuleFactory.js:882:8
at /data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/webpack/lib/NormalModuleFactory.js:1002:5
Full Error details:
ModuleNotFoundError: Module not found: Error: Can't resolve '../../../../scenery-phet/js/accessibility/describers/MovementDescriber.js' in '/data/share/phet/continuous-testing/ct-snapshots/1629969913512/greenhouse-effect/js/micro/view'

Webpack build errors: [
ModuleNotFoundError: Module not found: Error: Can't resolve '../../../../scenery-phet/js/accessibility/describers/MovementDescriber.js' in '/data/share/phet/continuous-testing/ct-snapshots/1629969913512/greenhouse-effect/js/micro/view'
at /data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/webpack/lib/Compilation.js:1773:28
at /data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/webpack/lib/NormalModuleFactory.js:811:13
at eval (eval at create (/data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
at /data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/webpack/lib/NormalModuleFactory.js:286:22
at eval (eval at create (/data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
at /data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/webpack/lib/NormalModuleFactory.js:442:22
at /data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/webpack/lib/NormalModuleFactory.js:124:11
at /data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/webpack/lib/NormalModuleFactory.js:673:25
at /data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/webpack/lib/NormalModuleFactory.js:882:8
at /data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/webpack/lib/NormalModuleFactory.js:1002:5
resolve '../../../../scenery-phet/js/accessibility/describers/MovementDescriber.js' in '/data/share/phet/continuous-testing/ct-snapshots/1629969913512/greenhouse-effect/js/micro/view'
using description file: /data/share/phet/continuous-testing/ct-snapshots/1629969913512/greenhouse-effect/package.json (relative path: ./js/micro/view)
Field 'browser' doesn't contain a valid alias configuration
using description file: /data/share/phet/continuous-testing/ct-snapshots/1629969913512/scenery-phet/package.json (relative path: ./js/accessibility/describers/MovementDescriber.js)
no extension
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/1629969913512/scenery-phet/js/accessibility/describers/MovementDescriber.js doesn't exist
.js
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/1629969913512/scenery-phet/js/accessibility/describers/MovementDescriber.js.js doesn't exist
.json
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/1629969913512/scenery-phet/js/accessibility/describers/MovementDescriber.js.json doesn't exist
.wasm
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/1629969913512/scenery-phet/js/accessibility/describers/MovementDescriber.js.wasm doesn't exist
as directory
/data/share/phet/continuous-testing/ct-snapshots/1629969913512/scenery-phet/js/accessibility/describers/MovementDescriber.js doesn't exist,
ModuleNotFoundError: Module not found: Error: Can't resolve '../../../../scenery-phet/js/accessibility/describers/MovementDescriber.js' in '/data/share/phet/continuous-testing/ct-snapshots/1629969913512/greenhouse-effect/js/micro/view'
at /data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/webpack/lib/Compilation.js:1773:28
at /data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/webpack/lib/NormalModuleFactory.js:811:13
at eval (eval at create (/data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
at /data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/webpack/lib/NormalModuleFactory.js:286:22
at eval (eval at create (/data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
at /data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/webpack/lib/NormalModuleFactory.js:442:22
at /data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/webpack/lib/NormalModuleFactory.js:124:11
at /data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/webpack/lib/NormalModuleFactory.js:673:25
at /data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/webpack/lib/NormalModuleFactory.js:882:8
at /data/share/phet/continuous-testing/ct-snapshots/1629969913512/chipper/node_modules/webpack/lib/NormalModuleFactory.js:1002:5
resolve '../../../../scenery-phet/js/accessibility/describers/MovementDescriber.js' in '/data/share/phet/continuous-testing/ct-snapshots/1629969913512/greenhouse-effect/js/micro/view'
using description file: /data/share/phet/continuous-testing/ct-snapshots/1629969913512/greenhouse-effect/package.json (relative path: ./js/micro/view)
Field 'browser' doesn't contain a valid alias configuration
using description file: /data/share/phet/continuous-testing/ct-snapshots/1629969913512/scenery-phet/package.json (relative path: ./js/accessibility/describers/MovementDescriber.js)
no extension
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/1629969913512/scenery-phet/js/accessibility/describers/MovementDescriber.js doesn't exist
.js
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/1629969913512/scenery-phet/js/accessibility/describers/MovementDescriber.js.js doesn't exist
.json
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/1629969913512/scenery-phet/js/accessibility/describers/MovementDescriber.js.json doesn't exist
.wasm
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/1629969913512/scenery-phet/js/accessibility/describers/MovementDescriber.js.wasm doesn't exist
as directory
/data/share/phet/continuous-testing/ct-snapshots/1629969913512/scenery-phet/js/accessibility/describers/MovementDescriber.js doesn't exist
]
Snapshot from 8/26/2021, 3:25:13 AM
```

**Comment by marlitas** [comment]
This looks rather stale. Closing.
