### ISSUE TITLE
CT Assertion failed: phetioElement not found: 

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#395]
```
molecules-and-light : phet-io-studio-fuzz : unbuilt
https://sparky.colorado.edu/continuous-testing/ct-snapshots/1688154842092/studio/?sim=molecules-and-light&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecules-and-light%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1688154842092%22%2C%22timestamp%22%3A1688155494805%7D
Assertion failed: phetioElement not found: moleculesAndLight.moleculesAndLightScreen.view.lightSpectrumDialog.closeButton.firedEmitter
@https://sparky.colorado.edu/continuous-testing/ct-snapshots/1688154842092/assert/js/assert.js:28:22
at <unknown> (https://sparky.colorado.edu/continuous-testing/ct-snapshots/1688154842092/assert/js/assert.js:28:22)
at archetypePhetioElement (studio.ts:234:26)
at phetioID (studio-main.ts:53:31)
at (Client.ts:614:78)
at message (Client.ts:606:26)
at message (Client.ts:468:37)
at (Client.ts:434:61)
[URL] https://sparky.colorado.edu/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1688154842092%2Fstudio%2F%3Fsim%3Dmolecules-and-light%26phetioWrapperDebug%3Dtrue%26fuzz&testInfo=%7B%22test%22%3A%5B%22molecules-and-light%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1688154842092%22%2C%22timestamp%22%3A1688155494805%7D
[NAVIGATED] https://sparky.colorado.edu/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1688154842092%2Fstudio%2F%3Fsim%3Dmolecules-and-light%26phetioWrapperDebug%3Dtrue%26fuzz&testInfo=%7B%22test%22%3A%5B%22molecules-and-light%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1688154842092%22%2C%22timestamp%22%3A1688155494805%7D
[NAVIGATED] about:blank
[NAVIGATED] https://sparky.colorado.edu/continuous-testing/ct-snapshots/1688154842092/studio/?sim=molecules-and-light&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecules-and-light%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1688154842092%22%2C%22timestamp%22%3A1688155494805%7D
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] https://sparky.colorado.edu/continuous-testing/ct-snapshots/1688154842092/molecules-and-light/molecules-and-light_en.html?brand=phet-io&ea&debugger&postMessageOnError&sim=molecules-and-light&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecules-and-light%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1688154842092%22%2C%22timestamp%22%3A1688155494805%7D&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[CONSOLE] Assertion failed: phetioElement not found: moleculesAndLight.moleculesAndLightScreen.view.lightSpectrumDialog.closeButton.firedEmitter
[CONSOLE] Assertion failed: phetioElement not found: moleculesAndLight.moleculesAndLightScreen.view.lightSpectrumDialog.closeButton.pressListener.pressAction
[CONSOLE] Assertion failed: phetioElement not found: moleculesAndLight.moleculesAndLightScreen.view.lightSpectrumDialog.closeButton.pressListener.pressAction.executedEmitter
[CONSOLE] Assertion failed: phetioElement not found: moleculesAndLight.moleculesAndLightScreen.view.lightSpectrumDialog.closeButton.pressListener.releaseAction
[CONSOLE] Assertion failed: phetioElement not found: moleculesAndLight.moleculesAndLightScreen.view.lightSpectrumDialog.closeButton.pressListener.releaseAction.executedEmitter
[CONSOLE] Assertion failed: phetioElement not found: moleculesAndLight.moleculesAndLightScreen.view.lightSpectrumDialog.closeButton
[CONSOLE] Assertion failed: phetioElement not found: moleculesAndLight.moleculesAndLightScreen.view.lightSpectrumDialog
[CONSOLE] Assertion failed: phetioElement not found: moleculesAndLight.moleculesAndLightScreen.view.lightSpectrumDialog.isShowingProperty
[PAGE ERROR] Unhandled Promise Rejection: Error: Assertion failed: phetioElement not found: moleculesAndLight.moleculesAndLightScreen.view.lightSpectrumDialog.closeButton.firedEmitter
[PAGE ERROR] Unhandled Promise Rejection: Error: Assertion failed: phetioElement not found: moleculesAndLight.moleculesAndLightScreen.view.lightSpectrumDialog.closeButton.pressListener.pressAction
[PAGE ERROR] Unhandled Promise Rejection: Error: Assertion failed: phetioElement not found: moleculesAndLight.moleculesAndLightScreen.view.lightSpectrumDialog.closeButton.pressListener.pressAction.executedEmitter
[PAGE ERROR] Unhandled Promise Rejection: Error: Assertion failed: phetioElement not found: moleculesAndLight.moleculesAndLightScreen.view.lightSpectrumDialog.closeButton.pressListener.releaseAction
[PAGE ERROR] Unhandled Promise Rejection: Error: Assertion failed: phetioElement not found: moleculesAndLight.moleculesAndLightScreen.view.lightSpectrumDialog.closeButton.pressListener.releaseAction.executedEmitter
[PAGE ERROR] Unhandled Promise Rejection: Error: Assertion failed: phetioElement not found: moleculesAndLight.moleculesAndLightScreen.view.lightSpectrumDialog.closeButton
[PAGE ERROR] Unhandled Promise Rejection: Error: Assertion failed: phetioElement not found: moleculesAndLight.moleculesAndLightScreen.view.lightSpectrumDialog
[PAGE ERROR] Unhandled Promise Rejection: Error: Assertion failed: phetioElement not found: moleculesAndLight.moleculesAndLightScreen.view.lightSpectrumDialog.isShowingProperty
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error

id: "Safari from Node"
Snapshot from 6/30/2023, 1:54:02 PM
```

**Comment by jessegreenberg** [comment]
Closing, this has since gone away on CT.
