### ISSUE TITLE
CT: Assertion failed: reentry detected, value=SINGLE_O2_MOLECULE, oldValue=SINGLE_CH4_MOLECULE

### ISSUE THREAD

**Issue by jbphet** [phetsims/molecules-and-light#398]
There is a periodic failure on CT with the following info:

```
molecules-and-light : fuzz : unbuilt : listenerOrderRandom
http://128.138.93.172/continuous-testing/ct-snapshots/1696005275560/molecules-and-light/molecules-and-light_en.html?continuousTest=%7B%22test%22%3A%5B%22molecules-and-light%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1696005275560%22%2C%22timestamp%22%3A1696006036024%7D&brand=phet&ea&fuzz&listenerOrder=random
Query: brand=phet&ea&fuzz&listenerOrder=random
Uncaught Error: Assertion failed: reentry detected, value=SINGLE_O2_MOLECULE, oldValue=SINGLE_CH4_MOLECULE
Error: Assertion failed: reentry detected, value=SINGLE_O2_MOLECULE, oldValue=SINGLE_CH4_MOLECULE
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1696005275560/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:311:14)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:65:10)
at set (RectangularRadioButton.ts:148:50)
at listener (TinyEmitter.ts:123:8)
at emit (Emitter.ts:61:21)
at emit (RectangularRadioButton.ts:184:24)
at fire (RectangularRadioButton.ts:153:13)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1696005275560%2Fmolecules-and-light%2Fmolecules-and-light_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22molecules-and-light%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1696005275560%22%2C%22timestamp%22%3A1696006036024%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1696005275560%2Fmolecules-and-light%2Fmolecules-and-light_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22molecules-and-light%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1696005275560%22%2C%22timestamp%22%3A1696006036024%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1696005275560/molecules-and-light/molecules-and-light_en.html?continuousTest=%7B%22test%22%3A%5B%22molecules-and-light%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1696005275560%22%2C%22timestamp%22%3A1696006036024%7D&brand=phet&ea&fuzz&listenerOrder=random
[CONSOLE] enabling assert
[CONSOLE] listenerOrder random seed: 514106
[CONSOLE] continuous-test-load
```

**Comment by jbphet** [comment]
Turning off the random listener order test for the photon target (see https://github.com/phetsims/greenhouse-effect/commit/c8a3af3af722cae0ffaf64334674a4939b108c00) appears to have resolved this problem.  Closing.
