### ISSUE TITLE
CT: Cannot add a listener to a disposed TinyEmitter

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#400]
```
molecules-and-light : phet-io-state-fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1715015992095/phet-io-wrappers/state/?sim=molecules-and-light&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecules-and-light%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1715015992095%22%2C%22timestamp%22%3A1715016811875%7D
Uncaught Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1715015992095/assert/js/assert.js:28:13)
at assert (dataStream.ts:299:14)
at end (PhetioObject.ts:514:29)
at phetioEndEvent (phetioCommandProcessor.ts:254:17)
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1715015992095%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dmolecules-and-light%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&testInfo=%7B%22test%22%3A%5B%22molecules-and-light%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1715015992095%22%2C%22timestamp%22%3A1715016811875%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1715015992095%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dmolecules-and-light%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&testInfo=%7B%22test%22%3A%5B%22molecules-and-light%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1715015992095%22%2C%22timestamp%22%3A1715016811875%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1715015992095/phet-io-wrappers/state/?sim=molecules-and-light&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecules-and-light%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1715015992095%22%2C%22timestamp%22%3A1715016811875%7D
[ATTACHED]
[NAVIGATED] about:blank
[ATTACHED]
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1715015992095/molecules-and-light/molecules-and-light_en.html?brand=phet-io&ea&postMessageOnError&sim=molecules-and-light&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecules-and-light%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1715015992095%22%2C%22timestamp%22%3A1715016811875%7D&frameTitle=source
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1715015992095/molecules-and-light/molecules-and-light_en.html?brand=phet-io&ea&postMessageOnError&sim=molecules-and-light&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecules-and-light%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1715015992095%22%2C%22timestamp%22%3A1715016811875%7D&frameTitle=destination
[CONSOLE] enabling assert
[CONSOLE] enabling assert
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed: Cannot add a listener to a disposed TinyEmitter
[CONSOLE] Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
[PAGE ERROR] Error: Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1715015992095/assert/js/assert.js:28:13)
at DataStream.end (http://128.138.93.172/continuous-testing/ct-snapshots/1715015992095/chipper/dist/js/phet-io/js/dataStream.js:253:15)
at PhetioCommandProcessor.phetioEndEvent (http://128.138.93.172/continuous-testing/ct-snapshots/1715015992095/chipper/dist/js/tandem/js/PhetioObject.js:439:30)
at http://128.138.93.172/continuous-testing/ct-snapshots/1715015992095/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:135:18
[PAGE ERROR] Error: Error: Assertion failed: Cannot add a listener to a disposed TinyEmitter
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1715015992095/assert/js/assert.js:28:13)
at TinyProperty.addListener (http://128.138.93.172/continuous-testing/ct-snapshots/1715015992095/chipper/dist/js/axon/js/TinyEmitter.js:199:15)
at BooleanProperty.link (http://128.138.93.172/continuous-testing/ct-snapshots/1715015992095/chipper/dist/js/axon/js/ReadOnlyProperty.js:352:23)
at new MoleculeNode (http://128.138.93.172/continuous-testing/ct-snapshots/1715015992095/chipper/dist/js/greenhouse-effect/js/micro/view/MoleculeNode.js:65:48)
at addMoleculeToWindow (http://128.138.93.172/continuous-testing/ct-snapshots/1715015992095/chipper/dist/js/greenhouse-effect/js/micro/view/MicroObservationWindow.js:128:28)
at TinyEmitter.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1715015992095/chipper/dist/js/axon/js/TinyEmitter.js:176:7)
at TinyEmitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1715015992095/chipper/dist/js/axon/js/TinyEmitter.js:161:14)
at Emitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1715015992095/chipper/dist/js/axon/js/Emitter.js:52:22)
at http://128.138.93.172/continuous-testing/ct-snapshots/1715015992095/chipper/dist/js/axon/js/createObservableArray.js:111:58
at Proxy.setNotificationsDeferred (http://128.138.93.172/continuous-testing/ct-snapshots/1715015992095/chipper/dist/js/axon/js/createObservableArray.js:419:37)
[PAGE ERROR] Error: Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1715015992095/assert/js/assert.js:28:13)
at DataStream.end (http://128.138.93.172/continuous-testing/ct-snapshots/1715015992095/chipper/dist/js/phet-io/js/dataStream.js:253:15)
at PhetioCommandProcessor.phetioEndEvent (http://128.138.93.172/continuous-testing/ct-snapshots/1715015992095/chipper/dist/js/tandem/js/PhetioObject.js:439:30)
at http://128.138.93.172/continuous-testing/ct-snapshots/1715015992095/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:135:18
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 5/6/2024, 11:19:52 AM
```

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe. I am not sure how to investigate this. I don't see recent changes in greenhouse-effect or this repo so it is likely another common code change. I am also not sure how to reproduce this error.

@zepumph or @samreid can you please advise?

**Comment by zepumph** [comment]
We will take a look. It was caused by work over in https://github.com/phetsims/phet-io/issues/1661. Sorry for the trouble.

**Comment by samreid** [comment]
@zepumph and I pushed a proposed fix. @zepumph will check CT in a few columns to see how it goes.

**Comment by zepumph** [comment]
CT is clear
